services:
  backend:
    build: 
      context: ./AppMonitoringService.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    expose:
      - "80"
    networks:
      - app-network
    volumes:
      - ./AppMonitoringService.API/devices_backup:/app/devices_backup:rw
 
  frontend:
    build: 
      context: ./AppMonitoringService.UI
    ports:
      - "80:80" 
    volumes:
      - ./AppMonitoringService.UI/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge