FROM node:22.12 AS build
WORKDIR /app

# 1. Сначала копируем только файлы зависимостей
COPY package.json package-lock.json ./

# 2. Устанавливаем ВСЕ зависимости (включая devDependencies)
RUN npm install --include=dev --force

# 3. Копируем остальные файлы проекта
COPY . .

# 4. Собираем проект 
RUN npm run build --configuration=production

# 5. Финальный образ с nginx
FROM nginx:alpine
COPY --from=build /app/dist/app-monitoring-service-ui /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80