# Используем официальный образ SDK для сборки
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Копируем файлы проекта и восстанавливаем зависимости
COPY ["AppMonitoringService.API.csproj", "."]
RUN dotnet restore "AppMonitoringService.API.csproj"

# Копируем остальные файлы и собираем проект
COPY . .
RUN dotnet build "AppMonitoringService.API.csproj" -c Release -o /app/build
RUN dotnet publish "AppMonitoringService.API.csproj" -c Release -o /app/publish

# Используем официальный образ рантайма
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Открываем порт, который использует ваше API
EXPOSE 7164
ENTRYPOINT ["dotnet", "AppMonitoringService.API.dll"]